### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by mdenty** [tessi-lab/ml-bench#1]
Install both TensorFlow and OpenCV on Apple Silicon seems broken.

I have no such computer.

**Comment by antond** [comment]
FWIW, I followed the install instructions in the README (from scratch, with `miniforge` installed via homebrew) on a MacBook 2021 16' - M1 Max - 32 GB RAM - SSD 1 TB and plugged to the wall. It worked and I got the following results at 20 epochs normal:
```
************
**  DONE  **
************
LOAD_TRAIN: 3193 ms
CREATE_TRAIN: 6344 ms
LOAD_TEST: 514 ms
CREATE_TEST: 531 ms
TRAIN: 37583 ms
```
