### ISSUE TITLE
no wxpython package for apple silicon available

### ISSUE THREAD

**Issue by miloshev** [tessi-lab/ml-bench#6]
When i try to install: conda install -c apple wxpython
I get error
PackagesNotFoundError: The following packages are not available from current channels:

  - wxpython

Current channels:

  - https://conda.anaconda.org/apple/osx-arm64
  - https://conda.anaconda.org/apple/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

Any idea how to fix it ?

**Comment by xvolks** [comment]
Hello,

I've just tested the following :
```
conda create -n ml-bench python=3.9
conda activate ml-bench
conda install -c apple wxpython
```

It just worked as expected.
Did you installed `conda` with `miniforge3` ?
